---
title: "Risk Scenario Explorer"
author: "Evaluator toolkit"
output:
  flexdashboard::flex_dashboard:
    vertical-layout: fill
    favicon: ./img/evaluator_logo_48px.png
    logo: ./img/evaluator_logo_48px.png
    navbar:
    - align: right
      href: https://github.com/davidski/evaluator
      title: About
    orientation: columns
    css: styles/html-styles.css
runtime: shiny
---

```{r setup, include=FALSE}
# Load packages and initialize data here
if ("pacman" %in% installed.packages()) {
  pacman::p_load(flexdashboard, ggplot2, extrafont, scales, viridis, stringi, dplyr)
  pacman::p_load(readr, tidyr, modeest, shiny, DT)
} else {
  library(flexdashboard)
  library(ggplot2)
  library(extrafont)
  library(scales)
  library(viridis)
  library(stringi)
  library(dplyr)
  library(readr)
  library(tidyr)
  library(modeest)
  library(shiny)
  library(DT)
}
knitr::read_chunk("./bin/load_data.R")
knitr::read_chunk("./bin/utils.R")
```

```{r load_data, include=FALSE}
```

```{r common_functions, include=FALSE}
```

```{r helper_functions, include=FALSE}
# determine the correct base font family to use
basefont <- get_base_fontfamily()

mappings <<- mappings
source("./bin/qual_to_quant.R")  # custom quant/qual conversions
# for values stored as full precentages, divide by 100 and pretty format 
# with scales::percent()
custom_percent <- function(x) {
    x <- as.integer(x)
    return(percent(x/100 %>% round(digits = 2)))
}

get_loss_table <- function(tid) {
  scenario_data <- results[results$scenario_id == tid, ]
  loss_table <- data_frame(Category = c("Loss Events / Year", "Loss Magnitude", 
                                        "Total Loss Exposure"),
                           Minimum = c(min(scenario_data$loss_events), 
                                       min(scenario_data$sle_min) %>% dollar,
                                       min(scenario_data$ale) %>% dollar),
                           Mean = c(mean(scenario_data$loss_events, na.rm = TRUE), 
                                    mean(scenario_data$sle_mean, na.rm = TRUE) %>% dollar,
                                    mean(scenario_data$ale, na.rm = TRUE) %>% dollar),
                           Mode = c(mfv(scenario_data$loss_events)[1], 
                                       mfv(scenario_data$sle_median)[1] %>% as.numeric %>% dollar,
                                       mfv(scenario_data$ale)[1] %>% as.numeric %>% dollar),
                           Maximum = c(max(scenario_data$loss_events), 
                                       max(scenario_data$sle_max) %>% dollar,
                                       max(scenario_data$ale) %>% dollar)
  )
  return(loss_table)
}

get_scenario_data <- function(sid){
  scenario_data <- results %>% filter(scenario_id == sid)
  return(scenario_data)
}

get_scenario_id <- function(x){
  scenario_id <- as.numeric(strsplit(x, " - ")[[1]][2])
  return(scenario_id)
}

get_summary_table <- reactive({
  #filter_input <- get_threat_id(input$input_threat)
  summary_data <- scenario_summary %>% filter(scenario_id == 
                                              get_scenario_id(input$input_scenario))
  # add pretty formatting
  summary_data <- mutate_each(summary_data, funs(dollar), 
                              c(ale_median, ale_max, ale_var, sle_mean, 
                                sle_median, sle_max, sle_min)) %>% 
     mutate(mean_tc_exceedance = custom_percent(mean_tc_exceedance)) %>% 
     mutate(mean_vuln = percent(mean_vuln))
  
  names(summary_data) <- stri_trans_totitle(gsub("_", " ", names(summary_data)))
  summary_data <- summary_data %>% mutate_each(funs(as.character)) %>% 
    gather(key = "Parameter", value = "Value")
  return(summary_data)
})

get_threat_table <- reactive({
  #filter_input <- get_threat_id(input$input_threat)
  threat_data <- scenarios %>%
    filter(scenario_id == get_scenario_id(input$input_scenario)) %>% 
    select(scenario_id, tef, tc) %>% 
    gather(type, label, c(tef, tc)) %>% 
    left_join(mappings, by = c("label" = "label", "type" = "type")) %>% 
    gather(param, value, c(l:conf)) %>% 
    mutate(value = ifelse(type == "tef" | param == "conf", 
                          as.integer(value), custom_percent(value))) %>% 
    spread(param, value) %>% 
    mutate(type = ifelse(type == "tc", "Capability", "Frequency"))
  threat_data <- threat_data %>% select(Type = type, Low = l, "Most Likely" = ml,
                                        "High" = h, Confidence = conf)
  return(threat_data)
})

get_control_table <- reactive({
  
  #filter_input <- get_threat_id(input$input_threat)
  control_list <- scenarios %>%
    filter(scenario_id == get_scenario_id(input$input_scenario)) %>% 
    select(controls) %>% stringi::stri_split_fixed(", ") %>% unlist()
  control_data <- capabilities[capabilities$id %in% as.numeric(control_list), "diff"] %>% 
    rename(label = diff) %>% 
    mutate(label = as.character(label)) %>% 
    convert_qual_to_quant(qual_type = "diff")
  #convert_qual_to_quant(capabilities[capabilities$id %in% 
  #                                          as.numeric(control_list), 
  #                                        "diff"]$diff)
  # format percentages
  control_data <- mutate_each(control_data, funs(custom_percent), -conf) %>%
    mutate(conf = as.integer(conf))
  control_data$control <- as.numeric(control_list)
  # add control description
  control_data <- left_join(control_data, capabilities, 
                            by = c("control" = "id")) %>% 
    select(Control = capability, Low = l, "Most Likely" = ml, High = h, 
           Confidence = conf)
  return(control_data)
})

get_loss_distribution_table <- reactive({
  #filter_input <- get_threat_id(input$input_threat)
  loss_list <- scenarios %>% 
    filter(scenario_id == get_scenario_id(input$input_scenario)) %>% 
    mutate(label = as.character(lm)) %>% 
    convert_qual_to_quant(qual_type = "lm") %>% 
    mutate_each(funs(dollar), c(l, ml, h)) %>% 
    select(Low = l, "Most Likely" = ml, "High" = h, "Confidence" = conf)
  return(loss_list)
})
```

All Scenarios {data-icon="fa-users" data-orientation=rows}
=======================================================================

Loss Distribution Scatterplot
-----------------------------------------------------------------------

### Loss Distributions Across All Threat Scenarios {.no-title}

```{r show_all_boxplot, fig.height=4}
renderPlot({
  gg <- ggplot(results, aes(x = as.character(scenario_id), y = ale))
  gg <- gg + scale_y_continuous(label = dollar_millions)
  gg <- gg + labs(x = "Risk Scenario", y = "Annual Loss")
  gg <- gg + stat_boxplot(geom = 'errorbar', width = 0.5)
  gg <- gg + geom_boxplot(fill = viridis(1), alpha = 1/3)
  gg <- gg + facet_grid(~ domain_id, scales = "free_x", space = "free_x", 
                        switch = "x")
  gg <- gg + theme_evaluator(base_family = basefont)
  gg <- gg + theme(panel.grid.major = element_blank())
  gg <- gg + theme(panel.grid.minor = element_blank())
  print(gg)
})
```

All Scenarios Data Table
-----------------------------------------------------------------------

### All Risk Scenarios

```{r show_all_table}
DT::renderDataTable({
 dat <- mutate_each(scenario_summary, funs(dollar), starts_with("ale"), 
             starts_with("sle")) %>% 
   mutate(loss_events_mean = comma(loss_events_mean)) %>% 
   mutate(mean_tc_exceedance = custom_percent(mean_tc_exceedance)) %>% 
   mutate(mean_vuln = percent(mean_vuln))
 names(dat) <- stri_trans_totitle(names(dat))
 DT::datatable(dat, rownames = FALSE,
               options = list( 
                 scrollX = TRUE,
                 sScrollY = "300px",
                 fixedColumns = list(leftColumns = 2)), 
               extensions = c("Scroller", "FixedColumns"))
})
```

Individual Risk Scenarios {data-icon="fa-user"}
=======================================================================


Input Sidebar {.sidebar data-width=500}
-----------------------------------------------------------------------
Select a specific risk scenario for detailed analysis.

```{r inputs}
scenario_input <- paste(scenario_summary$domain_id, "-",
                        scenario_summary$scenario_id)
selectInput("input_scenario", "Risk Scenario", scenario_input)
```

### Scenario Description
```{r scenario_details}
renderText({
  scenarios[scenarios$scenario_id == get_scenario_id(input$input_scenario), 
                "scenario"][[1]]
})
```


#### Threat Profile

```{r threat_profile}
renderText({
  paste("Community:", scenarios[scenarios$scenario_id == get_scenario_id(input$input_scenario),
                               "tcomm"])
})
renderTable({
  get_threat_table()
}, include.rownames = FALSE, width=500)
```

#### Controls

```{r controls}
renderTable({
  get_control_table()
}, include.rownames = FALSE, width=500)
```

#### Loss Magnitude

```{r loss_magnitude}
renderTable({
  get_loss_distribution_table()
}, include.rownames = FALSE, width=500)
```

> Simulation data generated on `r format(attr(results, "generated_on"), 
"%b %d, %Y %H:%M:%S")`

Main Display {data-width=450}
-----------------------------------------------------------------------

### Loss Scatterplot

```{r show_scatterplot}
renderPlot({
  
  # get scenario_id via input$bins from ui.R
  scenario_id <- get_scenario_id(input$input_scenario)
  plot_data    <- results[results$scenario_id == scenario_id, ]
  
  # draw the scatterplot for this threat scenario
  gg <- ggplot(plot_data, aes(x = loss_events, y = ale))
  gg <- gg + geom_point(alpha = 1/4)
  gg <- gg + scale_y_continuous(label = dollar_millions,
                                limits = c(NA, max(results$ale, na.rm = TRUE)))
  gg <- gg + scale_x_continuous(label = comma,
                                limits = c(NA, max(results$loss_events, na.rm = TRUE)))
  gg <- gg + labs(x = "Loss Frequency (Annualized)", y = "Total Annual Loss Size")
  #gg <- gg + geom_point(position = "jitter", alpha = 0.1)
  #gg <- gg + stat_bin2d(bins = 50) + scale_fill_gradient(low = 'lightblue', high = 'red')
  #gg <- gg + stat_binhex(bins = 50) + scale_fill_gradient(low = 'lightblue', high = 'red')
  #gg <- gg + geom_text(aes(label = threat_id), size = 4)
  #gg <- gg + scale_x_log10(labels = comma) + scale_y_log10(labels = comma)
  gg <- gg + theme_evaluator(base_family = basefont)
  gg
})
```

### Value at Risk

```{r var_values}
renderValueBox({
  scenario_id <- get_scenario_id(input$input_scenario)
  scenario_data <- get_scenario_data(scenario_id)
  dat <- quantile(scenario_data$ale, 0.95, na.rm = TRUE)
  if(is.na(dat)) dat <- 0
  valueBox(dollar(dat),
           caption = "Value at Risk", icon = "fa-pencil", 
           color = ifelse(dat >= risk_tolerance[["high"]], "danger", ifelse(
             dat >= risk_tolerance[["medium"]], "warning", "success")))
})
```

### Vulnerability

```{r vuln_value}
renderValueBox({
  scenario_id <- get_scenario_id(input$input_scenario)
  dat <- scenario_summary[scenario_summary$scenario_id == scenario_id,
                          "mean_vuln"]$mean_vuln
  if(is.na(dat)) dat <- 0
  valueBox(percent(dat),
           caption = "Vulnerability", icon = "ion-nuclear",
           color = ifelse(dat >= .75, "danger", ifelse(
             dat >= .50, "warning", "success")))
})
```

Detailed Display {data-width=350}
-----------------------------------------------------------------------

### Summary Data

```{r show_summary}
renderTable({
  get_summary_table()
}, include.rownames = FALSE)
```

### Loss Table

```{r show_loss_table}
# Code for Chart C

loss_table <- reactive({
  scenario_id <- get_scenario_id(input$input_scenario)
  get_loss_table(scenario_id)
})

renderTable({loss_table()}, include.rownames = FALSE)
```
