---
title: "Risk Dashboard"
author: "Evaluator toolkit"
output:
  flexdashboard::flex_dashboard:
    css: styles/html-styles.css
    favicon: ./img/evaluator_logo_48px.png
    logo: ./img/evaluator_logo_48px.png
    navbar:
    - align: right
      href: https://github.com/davidski/evaluator
      title: About
    orientation: row
    source_code: embed
    vertical_layout: fill
  pdf_document: default
---

Sample narrative section.

```{r setup, include=FALSE}
if ("pacman" %in% installed.packages()) {
  pacman::p_load(flexdashboard)
  pacman::p_load(ggplot2, scales, extrafont, viridis, dplyr, purrr, forcats)
  pacman::p_load(readr, pander)
} else  {
  library(flexdashboard)
  library(ggplot2)
  library(scales)
  library(extrafont)
  library(viridis)
  library(dplyr)
  library(purrr)
  library(forcats)
  library(readr)
  library(pander)
}
knitr::opts_chunk$set(echo = FALSE) 

knitr::read_chunk("./bin/load_data.R")
knitr::read_chunk("./bin/common_graphs.R")
knitr::read_chunk("./bin/utils.R")
```

```{r load_data, echo = FALSE, message = FALSE}
```

```{r calculate_domain_impact}
```

```{r calculate_weak_domains}
```

```{r common_functions}
```

```{r calculate_max_losses}
```

Risk Dashboard
=======================================================================

Value Boxes
-----------------------------------------------------------------------

### Aggregate 95% Value at Risk

````{r var_valuebox}
overall <- results %>% group_by(simulation) %>% 
                     summarize(ale = sum(ale)) %>% select(ale) %>%
                     ungroup
agg_risk <- quantile(overall$ale, 0.95)
valueBox(dollar_millions(agg_risk), icon = "glyphicon-eye-open",
         color = ifelse(agg_risk > risk_tolerance["high"], "danger", ifelse(
           agg_risk > risk_tolerance["medium"], "warning", "info")))
```

### Minimum Annual Loss (80% likelihood)

```{r ale_exceedance_valuebox}
loss_exceedance <- quantile(filter(max_loss, outliers==FALSE)$max_loss, .2)
valueBox(dollar_millions(loss_exceedance), icon = "glyphicon-warning-sign",
         color = ifelse(loss_exceedance > risk_tolerance["high"], "danger", ifelse(
           loss_exceedance > risk_tolerance["medium"], "warning", "info")))
```

### Median Loss Events per Year

```{r median_aggregate_loss_events}
loss_events <- group_by(results, simulation) %>% 
  summarise(n = sum(loss_events)) %>% summarize(loss = median(n)) %>% 
  unlist %>% unname
valueBox(comma(loss_events), icon = "glyphicon-flag",
         color = "info")

```

Domain Summary {data-height=150}
-----------------------------------------------------------------------

### Domain Heatmap {.no-padding}

```{r domain_heatmap, include = FALSE}
```

```{r display, fig.width=15, fig.height=1}
# modify the base plot for displaying on the dashboard
gg <- gg + labs(title = NULL, caption = NULL)
gg <- gg + theme(legend.position = "right")
gg <- gg + scale_fill_viridis(guide = FALSE, end = 0.75, option = "D")
gg <- gg + guides(fill = FALSE)
gg
```

Scenario Results {.data-height=250}
-----------------------------------------------------------------------

### Loss Ranges for Top 10 Scenarios {.no-padding}

```{r loss_across_scenarios, fig.width=10, fig.height=3, cache=TRUE}
# helper function to roll up scenarios that aren't in the top_n
sum_bottom_n <- function(dat, top_n=10, sortby="max_ale") {
  cluster_hack <- max(dat$cluster_id)
  full_label <- "full_label"
  
  # assign a flag on outliers
  keep_nokeep <- dat %>% group_by_(full_label) %>% 
    summarise_(foo= ~max(sortby)) %>% 
    mutate(keep = ifelse(row_number() <= top_n, TRUE, FALSE)) %>% 
    select(-foo)
  
  # sum up the outliers
  others <- filter(keep_nokeep, keep==FALSE) %>% 
    left_join(dat, by="full_label") %>% 
    group_by(simulation) %>% summarize(ale = max(ale), scenario_count = n()) %>% 
    mutate(full_label = paste0("others (", scenario_count, ")")) %>% 
    mutate(cluster_id = cluster_hack)
  
  # combine the outliers with the top_n items
  union_all(filter(keep_nokeep, keep==TRUE) %>% 
              left_join(dat, by="full_label"), others)
}

# assign the text label to scenarios and order
results %>% mutate(full_label = paste0(domain_id, " - ", scenario_id)) %>% 
  arrange(domain_id, scenario_id) -> dat 

# identify the top 10 scenarios by VaR
top_n_scenarios <- group_by(dat, full_label) %>% 
  summarize(ale_var = quantile(ale, 0.95)) %>% 
  filter(row_number(desc(ale_var)) <= 10 ) %>% 
  .[["full_label"]]

# remove no loss scenarios, enhance, and cluster
dat <- group_by(dat, full_label) %>% filter(sum(ale) != 0) %>% 
  mutate(var = quantile(ale, 0.95), max_ale = max(ale), ale_median = median(ale)) %>% 
  ungroup %>% 
  mutate(cluster_id = kmeans(max_ale, 3)$cluster)

# assign labels to the clusters
text_labels <- c("High", "Medium", "Low")
cluster_descriptions <- group_by(dat, cluster_id, full_label) %>% 
  summarize(ale = max(max_ale)) %>% 
  summarise(highest_ale = max(ale), n=n()) %>% 
  arrange(desc(highest_ale)) %>% 
  mutate(cluster_labels=factor(text_labels, levels = text_labels),
         top_n = min(last(n), n))

# roll up on a per-cluster basis, addng descriptive text to the cluster
summed_dat <- group_by(dat, cluster_id) %>% 
  left_join(cluster_descriptions, by="cluster_id") %>% 
  do(sum_bottom_n(., top_n=max(.$top_n))) %>% 
  select(-c(cluster_labels, n, top_n, highest_ale)) %>% 
  left_join(cluster_descriptions, by="cluster_id") %>% 
  ungroup

summed_dat <- group_by(summed_dat, full_label) %>% mutate(ale_median = median(ale))
  
# slimmed down alternative view of the dataset
minimal_dat <- filter(dat, full_label %in% top_n_scenarios, ale != 0) %>% 
  group_by(full_label) %>% 
  mutate(ale_median = median(ale)) %>% ungroup %>% 
  mutate(full_label = fct_reorder(full_label, ale_median))

# create sequential break points for our scale
minor_breaks <- map(seq(ceiling(log10(max(minimal_dat$ale)))), 
                    ~ cumsum(rep(10^.x, each=10))) %>% unique %>% unlist
minor_breaks <- minor_breaks[minor_breaks <= max(minimal_dat$ale)]

# plot!
gg <- ggplot(minimal_dat, aes(x = fct_reorder(full_label, desc(ale_median)), y = ale + 1))
#gg <- ggplot(summed_dat, aes(x = fct_reorder(full_label, ale_median), y = ale))

gg <- gg + stat_boxplot(geom = 'errorbar', width = 0.4)
#gg <- gg + geom_boxplot(aes(fill = keep), alpha = 1/3)
gg <- gg + geom_boxplot(fill = viridis(1), coef = 0, alpha = 1/3, outlier.shape = NA)
gg <- gg + scale_fill_viridis(discrete = TRUE)
#gg <- gg + facet_wrap(~ cluster_labels, nrow=1, scales = "free")
gg <- gg + scale_y_log10(label = dollar, minor_breaks = minor_breaks)
#gg <- gg + scale_y_log10(label = dollar, minor_breaks = seq(1, max(gg$data$ale), 100000))
gg <- gg + guides(fill = FALSE)
#gg <- gg + coord_flip()
gg <- gg + labs(x = NULL, y = "Annual\nLoss") 
gg <- gg + theme_evaluator()
gg <- gg + theme(panel.grid.major.x = element_line())
gg <- gg + theme(panel.grid.minor.x = element_line(color="grey92"))
#gg <- gg + theme(panel.grid.major = element_blank())
#gg <- gg + theme(panel.grid.minor = element_blank())
gg <- gg + theme(axis.title.y = element_text(angle = 0, vjust = 0.5, hjust = 0))
gg
```


Details
-----------------------------------------------------------------------

### Control Gaps/Surplus by Domain

```{r control_table}
select(control_weakness, domain, vuln, tc_exceedance, diff_exceedance) %>% 
  rename("Domain" = domain, 
       "Succesful Threat Events" = vuln,
       "Control Gap" = tc_exceedance,
       "Surplus Control Strength" = diff_exceedance) %>% 
  pander(justify = c("left", "right", "right", "right"), 
         split.cells = c(35, rep(10, 3)))
```

### Top Risk Scenarios

```{r top_risk_scenarios}
top_n(scenario_summary, 5, ale_var) %>% 
  arrange(desc(ale_var)) %>% 
  left_join(scenarios, by = c("scenario_id" = "scenario_id", 
                              "domain_id" = "domain_id")) %>%
  mutate(ale_var = dollar(ale_var), ale_median = dollar(ale_median),
         full_label = paste(domain_id, scenario_id, sep = " - ")) %>% 
  select("ID" = full_label, Scenario = scenario, 
         "Median Annual Loss" = ale_median, "Value at Risk" = ale_var) %>% 
  pander(justify = c(rep("left", 2), rep("right", 2)), split.cells=c(12, rep(30, 3)))
```
